# Generated by Django 4.1.7 on 2023-04-13 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_app', '0003_usermember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermember',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_app.course'),
        ),
        migrations.AlterField(
            model_name='usermember',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='usermember',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
